# Generated by Django 4.2.16 on 2026-04-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_department_course_grade_card_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=50),
        ),
    ]
