# Generated by Django 4.2.16 on 2026-04-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade_card_deadline',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='taassignment',
            name='can_assign_grades',
        ),
    ]
