# Generated by Django 4.2.16 on 2026-04-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_course_grade_card_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
