# Generated by Django 4.2.16 on 2026-04-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_exam_weightage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disabled', 'Disabled')], default='approved', max_length=20),
        ),
    ]
