# Generated by Django 4.2.16 on 2026-04-28 06:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerscript',
            name='file',
            field=models.FileField(upload_to=core.models.answer_script_upload_path),
        ),
    ]
